import React from 'react'
import Wrapper from '../../../_helpers/Wrapper'
import { Color } from '../Color'

export default {
  title: '👋 Get started/ Colors',
  component: Color,
  parameters: {
    docs: { 
        description: { 
            component: 'These are our five base colors: primary, black, dark, light and white. Additionally we got four colours for different events: success, notice, warning and error. Both base and event colors can be customized by providing a custom theme and will automatically create all these different shades.'
        } 
    },
  }
}

export const BaseColors = () => (
  <Wrapper>
    <Color
      color='var(--color-black)'
      colorLabel='Black'
      mainColor={true}
    />
    <Color
      color='var(--color-dark)'
      colorLabel='Dark'
      mainColor={true}
    />
    <Color
      color='var(--color-primary)'
      colorLabel='Primary'
      mainColor={true}
    />
    <Color
      color='var(--color-light)'
      colorLabel='Light'
      textColor='var(--color-black)'
      mainColor={true}
    />
    <Color
      color='var(--color-white)'
      colorLabel='White'
      textColor='var(--color-black)'
      mainColor={true}
    />
  </Wrapper>
)

export const Primary = () => (
  <Wrapper>
    <Color
      color='var(--color-primary-light)'
      colorLabel='-light'
    />
    <Color
      color='var(--color-primary)'
      colorLabel='Primary'
      mainColor={true}
    />
    <Color
      color='var(--color-primary-dark)'
      colorLabel='-dark'
    />
  </Wrapper>
)

export const Black = () => (
  <Wrapper>
    <Color
      color='var(--color-black)'
      colorLabel='Black'
      mainColor={true}
    />
    <Color
      color='var(--color-black-90)'
      colorLabel='-90'
    />
    <Color
      color='var(--color-black-80)'
      colorLabel='-80'
    />
    <Color
      color='var(--color-black-70)'
      colorLabel='-70'
    />
    <Color
      color='var(--color-black-60)'
      colorLabel='-60'
    />
    <Color
      color='var(--color-black-50)'
      colorLabel='-50'
    />
    <Color
      color='var(--color-black-40)'
      colorLabel='-40'
    />
    <Color
      color='var(--color-black-30)'
      colorLabel='-30'
    />
    <Color
      color='var(--color-black-20)'
      colorLabel='-20'
    />
    <Color
      color='var(--color-black-10)'
      colorLabel='-10'
    />
  </Wrapper>
)

export const Dark = () => (
  <Wrapper bgColor='black'>
    <Color
      color='var(--color-dark)'
      colorLabel='Dark'
      mainColor={true}
    />
    <Color
      color='var(--color-dark-90)'
      colorLabel='-90'
    />
    <Color
      color='var(--color-dark-80)'
      colorLabel='-80'
    />
    <Color
      color='var(--color-dark-70)'
      colorLabel='-70'
    />
    <Color
      color='var(--color-dark-60)'
      colorLabel='-60'
    />
    <Color
      color='var(--color-dark-50)'
      colorLabel='-50'
    />
    <Color
      color='var(--color-dark-40)'
      colorLabel='-40'
    />
    <Color
      color='var(--color-dark-30)'
      colorLabel='-30'
    />
    <Color
      color='var(--color-dark-20)'
      colorLabel='-20'
    />
    <Color
      color='var(--color-dark-10)'
      colorLabel='-10'
    />
  </Wrapper>
)

export const Light = () => (
  <Wrapper>
    <Color
      color='var(--color-light)'
      colorLabel='Light'
      textColor='var(--color-black)'
      mainColor={true}
    />
    <Color
      color='var(--color-light-90)'
      colorLabel='-90'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-light-80)'
      colorLabel='-80'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-light-70)'
      colorLabel='-70'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-light-60)'
      colorLabel='-60'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-light-50)'
      colorLabel='-50'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-light-40)'
      colorLabel='-40'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-light-30)'
      colorLabel='-30'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-light-20)'
      colorLabel='-20'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-light-10)'
      colorLabel='-10'
      textColor='var(--color-black)'
    />
  </Wrapper>
)

export const White = () => (
  <Wrapper>
    <Color
      color='var(--color-white)'
      colorLabel='White'
      textColor='var(--color-black)'
      mainColor={true}
    />
    <Color
      color='var(--color-white-90)'
      colorLabel='-90'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-white-80)'
      colorLabel='-80'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-white-70)'
      colorLabel='-70'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-white-60)'
      colorLabel='-60'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-white-50)'
      colorLabel='-50'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-white-40)'
      colorLabel='-40'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-white-30)'
      colorLabel='-30'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-white-20)'
      colorLabel='-20'
      textColor='var(--color-black)'
    />
    <Color
      color='var(--color-white-10)'
      colorLabel='-10'
      textColor='var(--color-black)'
    />
  </Wrapper>
)

export const Success = () => (
  <Wrapper>
    <Color
      color='var(--color-success-light)'
      colorLabel='-light'
    />
    <Color
      color='var(--color-success)'
      colorLabel='Success'
      mainColor={true}
    />
    <Color
      color='var(--color-success-dark)'
      colorLabel='-dark'
    />
  </Wrapper>
)

export const Notice = () => (
  <Wrapper>
    <Color
      color='var(--color-notice-light)'
      colorLabel='-light'
    />
    <Color
      color='var(--color-notice)'
      colorLabel='Notice'
      mainColor={true}
    />
    <Color
      color='var(--color-notice-dark)'
      colorLabel='-dark'
    />
  </Wrapper>
)

export const Warning = () => (
  <Wrapper>
    <Color
      color='var(--color-warning-light)'
      colorLabel='-light'
    />
    <Color
      color='var(--color-warning)'
      colorLabel='Warning'
      mainColor={true}
    />
    <Color
      color='var(--color-warning-dark)'
      colorLabel='-dark'
    />
  </Wrapper>
)

export const Error = () => (
  <Wrapper>
    <Color
      color='var(--color-error-light)'
      colorLabel='-light'
    />
    <Color
      color='var(--color-error)'
      colorLabel='Error'
      mainColor={true}
    />
    <Color
      color='var(--color-error-dark)'
      colorLabel='-dark'
    />
  </Wrapper>
)